### ISSUE TITLE
What's Center for and where is Elevator.origin

### ISSUE THREAD

**Issue by AntSharK** [AntSharK/MyFirstGame#21]
why is center not origin etc.

**Comment by AntSharK** [comment]
I'm trying to get the camera to follow the origin and only can follow the center.

**Comment by vijaypemmaraju** [comment]
think of origin as the local coordinate center (i.e, if top left corner of sprite was (0,0)). Center is the actual center point of the sprite in the game world (accounts for scale).

**Comment by AntSharK** [comment]
So Center is in screen coordinates. Righto, that's what confused me.
