### ISSUE TITLE
[BUG] Holding up or down during the elevator's deceleration freezes the animation

### ISSUE THREAD

**Issue by vijaypemmaraju** [AntSharK/MyFirstGame#7]
How to reproduce:
1.) Press up or down until accelerating
2.) Release and immediately press and hold up or down.
3.) The elevator will make it to the last frame of deceleration and get stuck. Velocity remains constant.
4.) Letting go will bring the elevator back to idle state.

Reproducibility: 10/10

**Comment by AntSharK** [comment]
expected - was more to test animation transition than anything.

**Comment by AntSharK** [comment]
TODO: Re-factor elevator into proper code.

**Comment by AntSharK** [comment]
Can you close this if it's resolved?
